(******************************************************************************)
(*                                                                            *)
(*              Deterministic Event-Stream Canonicalization                   *)
(*                                                                            *)
(*     Duplication, reordering, gaps, corrections, and cancels over a         *)
(*     raw event stream reduced to a canonical truth stream. Determinism,     *)
(*     idempotence, and online-offline equivalence. Canonicalize extracts     *)
(*     pure and idempotent; fold_stream matches batch by construction.        *)
(*     Serves as the replay-safe ingestion layer for any data product         *)
(*     or analytics pipeline that must be bit-for-bit reproducible.           *)
(*                                                                            *)
(*     "No man ever steps in the same river twice, for it is not the          *)
(*     same river and he is not the same man."                                *)
(*     – Heraclitus, c. 500 BC                                                *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: February 10, 2026                                                *)
(*     License: Proprietary — All Rights Reserved                             *)
(*                                                                            *)
(******************************************************************************)
